### ISSUE TITLE
Allow cancelling/hiding ActionSheetIOS

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [react-native-community/discussions-and-proposals#105]
### Introduction

The current implementation of ActionSheetIOS does not support a way to destroy the current ActionSheet programmatically. Therefore, the only way to dismiss it is to tap on one of the options.

### The Core of It

As of now, it is also possible to open multiple ActionSheets, appearing one on top of another. This results in odd behaviors. There should be only one ActionSheet at any time.

A better implementation would support a way to dismiss an opened ActionSheet.

I hence propose two possible solutions, depending if we want to keep multiple ActionSheets or just one.

1. Forcing to have at most one ActionSheet opened at any time and creating a method `dismiss()` which would destroy the current ActionSheet.

2. Support multiple ActionSheets and create a method `dismissLast()` which would destroy the last ActionSheet and a method `dismissAll()` to destroy all of them.

### Discussion points

I prefer the first option by forcing one ActionSheet at a time and creating the method `dismiss()`.
However, iOS does not specify if it's possibe to have multiple ones in the [guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/), so I leave the discussion open to that possibility.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

You may also want to check out the [Lean Core umbrella issue](https://github.com/facebook/react-native/issues/23313) because ActionSheet is going to be extracted from the main repo.
