### ISSUE TITLE
Move the TypeScript template to the community

### ISSUE THREAD

**Issue by emin93** [react-native-community/discussions-and-proposals#135]
### Introduction

Hi everyone,

Thank you all for the great effort you've spent into making React Native such a blast to work with everyday 🙂.

I'm not sure if this is the correct place to discuss this topic but I feel like it's more ideal than the meta repository (https://github.com/react-native-community/.github). Just let me know.

### The Core of It

About a year ago I created the [React Native TypeScript template](https://github.com/emin93/react-native-template-typescript) with the goal to offer an elegant way to start a new project with TypeScript while staying consistent with the default template and keeping the additional dependencies to a minimum.

Since then a lot of things have changed, especially with the introduction of Babel 7. I've been working hard to always keep up with the changes and make the template compatible with the most recent versions of React Native and the CLI.

According to the npm stats, the template is being used by a decent amount of people (currently at around 500 weekly downloads).

As React Native evolves really quickly, it is inevitable for me as an individual to sometimes fail catching up with the latest changes. I feel like the time has come to involve the React Native Community as this would allow me to go on vacation without having to worry about breaking changes 😄. Therefore I'd like to discuss this here.

### Discussion points

- Does it make sense?
- How to proceed?

**Comment by kelset** [comment]
👋 Emin!

Thanks for your hard work on this - I wasn't aware of this template because I don't use TS but it looks great!

Just for me to better understand, what you are asking here is to move your repo over the community and maybe find some co-maintainers, correct?

Or, like, to bundle/integrate this template in the new CLI? I am aware that they did some changes on that aspect but I don't know the details

**Comment by emin93** [comment]
Hey Lorenzo 🙂

Thanks for the kind words!

Yes exactly, the RN community is full of awesome people and I am hoping to find some that are willing to co-maintain, by moving the repo over 😄.

I saw them referencing the template in the new v2 docs (https://github.com/react-native-community/cli/blob/v2.0.0-rc.2/docs/init.md#initializing-project-with-custom-template) and doing some changes regarding the post installation script, which I use in the template, but I didn't know they are working on integrating it in the new CLI.

**Comment by kelset** [comment]
yo - sorry for the late reply!
I've asked around to better understand the CLI situation and I think that we can move the repo to the RNCOmm, but in terms of support for the new CLI I've been told this

>  he can also make a separate branch with a new template and publish it to something like next tag, keeping separate templates for separate RN versions is now also a thing, since we copy whole directory now

if that's ok for you then, because of admin reasons, I'd need you to migrate your repo to me so that then I can migrate it to the RNComm and once that's done I'll give you admin auth over it & invite you to the org.
Also, can you please DM me [on twitter](https://twitter.com/Kelset) so that I can invite you to the Discord?

**Comment by emin93** [comment]
No worries mate 🙂

Cool, thanks for the clarification! 🎉 

[Separate branch](https://github.com/emin93/react-native-template-typescript/tree/cli-v2) with the changes for the new CLI has been created already but it's not production ready yet. I think as long as the transition from CLI v1 to v2 is in progress, we'll have to maintain two versions of the template. Or maybe detect it in the post install script but I'd like to not do so as it'll start to become messy. Anyway, that's another topic which should be discussed in the template repo 😄.
