### ISSUE TITLE
React Native own rendering engine

### ISSUE THREAD

**Issue by haddad-yacine** [react-native-community/discussions-and-proposals#155]
Why don't react native team create his own view rendering engine like Flutter do?

**Comment by pvinis** [comment]
Because that's exactly what React Native doesn't want to do. It's a layer on top of existing rendering engines, same as with the web, and with native for ios and android. You can get the benefits of these existing underlying engines.

Flutter went the other way and decided to recreate everything. Basically what you want is Flutter + JSX, right?

**Comment by kelset** [comment]
(this feels more of a question than an actual in depth conversation, so I'm going to close it - but feel free to talk more)

(that said, yes basically what @pvinis is saying is my understanding on the topic too - btw, there are other conversations tangential to this that you may want to check: https://github.com/react-native-community/discussions-and-proposals/issues/153)
