### ISSUE TITLE
Move The Twitter Sign In Library Here

### ISSUE THREAD

**Issue by thecodecafe** [react-native-community/discussions-and-proposals#173]
### Introduction
Move The [Twitter Sign In Library](https://github.com/GoldenOwlAsia/react-native-twitter-signin) Here.

### The Core of It
There this library that allows developers to implement twitter sign in on their mobile app, it currently seems abandoned as there are many opened issues about the library that are very core to the functionality of the library that are not being addressed, for example, the library fails to build when you want to build a release APK for your android app, the current solution is to use a forked version of the library, there are also missing data from when a user's logs in like the name and avatar of the user, these two have been ignored and no one is saying a word about them, [here's the library](https://github.com/GoldenOwlAsia/react-native-twitter-signin).

### Discussion points
The library is awesome but it seems the people managing it are really busy right now will be awesome and helpful to have a more managed react-native twitter login library added to the react-community repo, situations like this make me wish I knew how to write native code.

**Comment by kelset** [comment]
👋 to make this happen, I think that the first step to take is to open an issue in said repo and make sure that the maintainers are ok with this idea.

Because they need to be involved, ofc :) In particular, they have to then move the library to an owner of the RNCommunity org (like @cpojer or @grabbou) and then they have to move it into the org.

Also, new maintainers that will take care of the repo need to be found (and npm publishing permissions must be given to them too) - I guess that since you opened this issue you want to be the new maintainer?

**Comment by thecodecafe** [comment]
Alright @kelset will do just that. And yeah, I would like to be a maintainer, I don't write native code but don't mind learning to contribute.

**Comment by TheSavior** [comment]
Can you help us understand what you are looking to achieve by having it be in react-native-community rather than a separate repo? 

If the goal is just to have more maintainers, I don’t think that is a given by being part of the community org. We have a hard time as it is finding maintainers for the repos currently in the org. 

I’m nervous about the community org ingesting a ton of the modules in the community, especially the ones that are coming unsupported. That is more likely to reduce the quality of the brand react-native-community as well.

Also, it looks like the official twitter sdk is [no longer supported by twitter](https://blog.twitter.com/developer/en_us/topics/tools/2018/discontinuing-support-for-twitter-kit-sdk.html). It feels a bit weird to me to want to move an unmaintained library built on top of a unsupported sdk into react-native-community.

What are your thoughts on this?

**Comment by rodperottoni** [comment]
Absolutely disagree with making third-party services SDKs part of the React Native Community.

**Comment by thecodecafe** [comment]
Hi @TheSavior the sole purpose of this is to have a library that is meant for solving that purpose, and that is supported by the community. Mostly when a person starts a library as a hobby, attending to issues, reviewing PRS, or updating to support changes within the platform they were built for can come in really late, and it's understandable, their main day job, takes priority because they need to keep things afloat for themselves, but my assumption before now is that it will be in the hands of a larger community so there will be more support, the only challenging thing I've seen so far is the sunsetting of the Twitter SDK, I don't know for how long iOS and Android will support its current codebase, so it's a bit of a demotivator, except that's managed by an open-source community as well, but still support for the library is what I'm trying to achieve with this.

**Comment by kelset** [comment]
I think we can close this since in its current configuration RNC doesn't host "third party modules" libraries anymore.
