### ISSUE TITLE
Add d3/svg maps

### ISSUE THREAD

**Issue by JoBerkner** [react-native-community/discussions-and-proposals#191]
### Introduction
I am a GIS developer (i.e. I make everything related to maps and location data). I am currently working on my very first React Native app but found out that I am not able to implement it the way I hoped I could.

### The Core of It
**Why would we need SVG maps?**
There are already ways to add SVG maps to React (e.g. [here](https://github.com/react-d3/react-d3-map) or [here](https://medium.com/@zimrick/how-to-create-pure-react-svg-maps-with-topojson-and-d3-geo-e4a6b6848a98)). The use cases for such maps are mostly for global accuracy (i.e. world maps) rather than detailed views of a specific area (for which the [react-native-maps](https://github.com/react-native-community/react-native-maps) library is already a great solution). Such maps can be especially helpful for data visualization purposes. 

**How does it currently work?**
It seems to be not possible atm. I myself implemented a map in React, but I am not able to reproduce this in React Native ([here is a question on StackOverflow related to my issue](https://stackoverflow.com/questions/59834577/how-to-add-an-svg-d3-map-to-react-native)).

**What do I propose?**
The [d3-geo](https://github.com/d3/d3-geo) implementation should be applied to React Native as well to add SVG maps.

### Discussion points

- Is there a general interest in adding SVG-based maps to React Native (preferably by implementing the logic from d3-geo)?
- Are there already resources of adding SVG maps to React Native (besides this library, which seems to be in an early beta version)?

**Comment by cpojer** [comment]
Hello @JoBerkner! Thanks for bringing up this issue and glad you are making progress on building your first app with React Native!

SVG Rendering is something that should be supported via third-party plugins instead of deep integration into RN’s core. RN should enable you to build such components, likely by exposing native components that render SVGs.

This repo is for discussions related to React Native’s core only. I’ll close the issue here.
