### ISSUE TITLE
Apps submitted to the App Store must use an Xcode storyboard to provide the app’s launch screen and all iPhone apps must support all iPhone screens.

### ISSUE THREAD

**Issue by codler** [react-native-community/discussions-and-proposals#209]
Will react native be affected by this news?
https://developer.apple.com/news/?id=03042020b

> Starting April 30, 2020, all iPhone apps submitted to the App Store must be built with the iOS 13 SDK or later.

> Starting April 30, 2020, all apps submitted to the App Store must use an Xcode storyboard to provide the app’s launch screen and all iPhone apps must support all iPhone screens.

**Comment by export-mike** [comment]
No you should be fine if your launch screen is created in storyboard afaik. See https://github.com/crazycodeboy/react-native-splash-screen/blob/master/README.md#installation using .xib file

**Comment by MoOx** [comment]
If I am correct .xib files are not storyboards. XIB is a legacy format. Storyboards have been introduced in iOS 5 SDK and I think this will become a real issue. RN provides by default a .xib and it might need to be changed in the template.

react-native-splash-screen doesn't support storyboards yet https://github.com/crazycodeboy/react-native-splash-screen/issues/115

but react-native-bootsplash will soon (already implemented in a branch as I am writing this, thanks @zoontek)  https://github.com/zoontek/react-native-bootsplash/issues/55

Maybe we should open an issue in RN repo, or directly make a PR?

**Comment by gwmccull** [comment]
my project is using `react-native-splash-screen` and we were able to switch to Storyboards for the launch screen with no issues, as were the other people in that thread
https://github.com/crazycodeboy/react-native-splash-screen/issues/115#issuecomment-586064671

but yes, the template should be changed

**Comment by zoontek** [comment]
@MoOx The new version of `react-native-bootsplash` using Storyboard as been published yesterday. The CLI handles .storyboard file generation automatically using a logo file and a background color.

`react-native-splash-screen` should support storyboard too I guess, because it achieve persistence by [blocking the UI main thread](https://github.com/crazycodeboy/react-native-splash-screen/blob/master/ios/RNSplashScreen.m#L29) (which can be dangerous - if it takes too long the system might kill it).

I agree that we should switch .storyboard by default, but we should also improve splash screen support out of the box: current implementations are difficult to setup.

The biggest pain is currently https://github.com/facebook/react-native/issues/9072 IMHO, but iOS setup could receive some love too (persisting the LaunchScreen storyboard until the JS finish loading, for example)

**Comment by radko93** [comment]
Just to be clear: xib files are still supported according to what was in Xcode 11 beta 4 changelog
> Your app might fail to build if it contains a launch image. The failure message resembles the following: “The launch image set named did not have any applicable content.” Launch images are deprecated and should be removed; use a launch storyboard or .xib file instead. (50210495)

**Comment by MoOx** [comment]
I don't think Xcode will support .xib for long.

- You cannot create a xib file using Xcode menu anymore
- If you have an existing .xib, you cannot find it & select it via the dropdown for the "Launch Screen File" option.

So for now, what is working is still working, yeah...

But that might be subject to change & you don't want to get a bad surprise starting may 2020...

**Comment by brynjar** [comment]
FWIW although File -> New only gives a LaunchScreen.storyboard option in turns of launch screens, you CAN still create xib files - both View and Empty under the User Interface section are .xibs (XC 11.4)

So my guess would be xib files will continue to be supported for some time.
Whether the Apple announcement means "you must use a storyboard or xib" Or "you must use a storyboard" is still not clear to me

**Comment by codler** [comment]
Fixed in 0.63-stable
