### ISSUE TITLE
Can we optimize the memory usage of websocket

### ISSUE THREAD

**Issue by Mollet-Yuan** [react-native-community/discussions-and-proposals#247]
I found that when using websocket, the application memory keeps growing (150 + MB on average), while when not using websocke, it performs well (60MB on average),

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. You should be posting this issue on the main [react native repo](https://github.com/facebook/react-native).

By doing so, and by following the template, you will help understanding the problem - because right now you are not giving any real information that could be used to test your assumptions.
