### ISSUE TITLE
Drop Android support for version < 5 (API level 21)

### ISSUE THREAD

**Issue by zoontek** [react-native-community/discussions-and-proposals#277]
### Introduction

We need to drop support for Android < 5. It's used by a very small percentage of users and hard to target since Material UI has been introduced with Android 5 Lollipop. Comparatively, iOS 8 & 9 (support already dropped by RN) has nearly the same amount of users worldwide as Android 4.1-4.4.

### Details

- If I refer to last month data on [StatCounter](https://gs.statcounter.com/android-version-market-share/mobile-tablet/worldwide/#monthly-202006-202008-bar), only 2,14% of the users worldwide are still on versions 4.1-4.4.
- Since the beginning, RN dropped support for iOS 8, and since 0.63, iOS 9, which both are still used by 2,05% of the users worldwide.

As Android Lollipop introduced a new UI and a bunch of new features, I think the core and a lot of community packages could be cleaned up if we do such a move 🔥. And styling default component will be easier too! (I'm looking a you, `TextInput` 👀)

<img width="378" alt="Screenshot 2020-09-24 at 11 23 28" src="https://user-images.githubusercontent.com/1902323/94127065-bfffa200-fe58-11ea-87d9-03a3c25f5304.png">

<img width="297" alt="Screenshot 2020-09-24 at 11 24 43" src="https://user-images.githubusercontent.com/1902323/94127074-c2fa9280-fe58-11ea-9ffd-b3cb996f7447.png">

### Discussion points

- How do we proceed ? Which steps are required ? (updating the core code, the documentation…)

**Comment by kelset** [comment]
A few thoughts:

1) Unless Facebook decides to proceed with this move, it's unlikely it will ever happen

2) Comparing percentages between iOS and Android is not that relevant, given how up to Aug 2020 Android has the [74.25% market share](https://gs.statcounter.com/os-market-share/mobile/worldwide); this means that 2% of Android is still massively more than 2% of iOS. (in broad strokes, it's basically x3 bigger in terms of absolute numbers). Statista says that Android users account for [1.6B users](https://www.statista.com/statistics/543185/worldwide-internet-connected-operating-system-population/) so 2% of that is around 32M users.

3) Another aspect around dropping iOS is that it's a limited number of devices that follow strictly Apple's policy on upgrading OS; Android, on the other hand, it's a massive mess.

**Comment by zoontek** [comment]
@kelset I'm guessing Facebook have metrics about real FB apps usage on these kind of devices. I would not be surprised if these users are barely active and use their phone for basic stuff like Phone & SMS.

I might be wrong but I hope not, because supporting old Android versions really is a pain point for the community. With Android 11 out lately, we have to test libs on Android 4 to 11. The fragmentation is huge.

**Comment by newyankeecodeshop** [comment]
Supporting Android 4.x also prevents React Native from upgrading to the latest OkHttp, which requires Android 5.x now.
https://github.com/square/okhttp#requirements
As they describe here:
> The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2021.

Lacking support for TLS 1.2 seems like a good reason to stop supporting Android 4.x too, whatever Facebook thinks.

**Comment by kelset** [comment]
Btw I went back to check in Android Studio (since turns out is now [the only place where you can find the official Android distribution from Google](https://www.xda-developers.com/android-version-distribution-statistics-android-studio/)) and it's not 2% as claimed above:

<img width="537" alt="Screenshot 2020-09-24 at 15 32 09" src="https://user-images.githubusercontent.com/16104054/94159425-72486100-fe7b-11ea-9530-e1bc9d4a2fba.png">

Sadly they decided to go for this kind of convoluted graph but what it means is that basically almost 6% of Android devices in the world are still under Android 5, with around a 4% on Android 4.4 in particular. So going back my my other data above around the 1.6B devices accounts to a 60M+ devices still in that Android 4.x.

**Comment by matt-oakes** [comment]
It should also be said that just because React Native itself supports back to API level 19, that doesn't mean your app or library needs to. You should obviously try to if possible, but if you have a critical feature that requires a newer API level then you can change the `minSdkVersion` in `android/build.gradle`.

To be fair though, the lack of support for up-to-date OkHTTP is a little troubling. What is the point where the React Native team would be happy to move to API 21 to get the latest OkHTTP?

**Comment by zoontek** [comment]
@kelset I don't think Google report active users. The usage numbers are pretty similar on [Statista](https://www.statista.com/statistics/921152/mobile-android-version-share-worldwide/) (for January 2020, which was 9 month ago) or a bit higher for [AppBrain SDK](https://www.appbrain.com/stats/top-android-sdk-versions) (3,6%), but not 6% either.

I agree that even if RN doesn't drop support for Android 4.x, we can encourage libs maintainers to drop it 🙂. I don't think Facebook would bother about it.

**Comment by TheSavior** [comment]
React Native maintains compatibility for whatever versions the Facebook app needs. If the Facebook app drops a version, that's when we drop a version. Since many parts of the Facebook app are written with React Native, we have to be usable across the range of devices used.

**Comment by zoontek** [comment]
For information: minSdk has been bumped to Android 21 (Lollipop) in RN 0.64
