### ISSUE TITLE
[Flat List] Add prop to renderItem when is rendered as sticky

### ISSUE THREAD

**Issue by mvehar** [react-native-community/discussions-and-proposals#297]
### Introduction

Flat List supports list of indices to define which items are sticky. I'm missing some property/argument for the renderItem to signal when some item is rendered as sticky (e.g. to adjust paddings, background etc.). 

### Details

- Pass **isSticky** prop to renderItem({item, index, separators, **isSticky**}) to signal when item is displayed as sticky

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

Or open a dedicated PR with the implementation against the main repo so that it can be discussed from a code perspective.
