### ISSUE TITLE
Support SVG files rendering

### ISSUE THREAD

**Issue by antoine-pous** [react-native-community/discussions-and-proposals#309]
### Introduction

SVG files are now massively used in any place on the web, even in mobile apps built using React Native. But actually RN does not provide a real way to deal with this kind of file. Instead we have to tweak with external dependencies which are more or less reliable.

### Details

Implementing the full support of SVG files, from both local and web sources, would be a major change for most of developers who need to create interface with scalable assets. It will avoid to use nondeterministic packages, which are good but not enough, and not able to deal the whole SVG specs.

### Discussion points

Would you see SVG file being managed by React Native instead of using external packages?

**Comment by kelset** [comment]
> Would you see SVG file being managed by React Native instead of using external packages?

I think the basic answer to this is that it depends on the needs of the FB team. Until then, 3rd party lib is the way I'm afraid.

**Comment by antoine-pous** [comment]
> > Would you see SVG file being managed by React Native instead of using external packages?
> 
> I think the basic answer to this is that it depends on the needs of the FB team. Until then, 3rd party lib is the way I'm afraid.

I doubt FB will continue to not use SVG in their products, then i think it would be really useful for their teams too, maybe am I wrong, but if we had a chance to get SVG rendered natively we have to seize it :grin:

**Comment by gwmccull** [comment]
I think the general philosophy has been more or less to only include in the React Native core libraries the components that are needed for nearly all apps on all platforms. Anything else is moved into a community supported library

I'm not a core maintainer but I don't think SVG is required for all apps and the community library seems to be well supported and stable, so I don't think SVG needs core support

**Comment by TheSavior** [comment]
AFAIK, rendering SVGs isn't something that is supported natively by both Android and iOS. If it was something the platforms could consistently just render, I'd expect the <Image> component to be able to handle rendering files with that extension.

However, since the platforms don't support that consistently, in order to render an SVG you have to bring in a custom library to do so. The SVG spec is quite massive. Even if core only implemented the 10% of the spec that 90% of people needed, we'd constantly get requests for implementing other features, which would require major app size increases that the other 90% would be justifiably upset about.

So instead of trying to solve this in core, the existence of 3rd party packages is quite nice here. People can have options in the implementation they choose. Something complete, or something minimal that meets their needs.
