### ISSUE TITLE
Box Shadow on Android as on Ios

### ISSUE THREAD

**Issue by fbeccaceci** [react-native-community/discussions-and-proposals#332]
### Introduction

The current situation of react native regarding shadows on android is quite embarassing, is not possibile to get great results having only the elvation prop to create the shadows we need. I would like to have the same props we can use to create shadows on ios on android, and they should also work with react-native-svg that on ios works great and i can add a shadow on a polygon while on android using elevation it doesn't work, but i don't know if this is more an issue related to react-native-svg or to this

### Discussion points
Creating a consistent way to create shadows across android and ios

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. I think you should be posting this as a PR against the main [react native repo](https://github.com/facebook/react-native) that the code details of such an implementation could be discussed further. I don't think this is necessarily an issue on rn-svg.

That's the only way it can be discussed & reviewed with the FB team.

**Comment by TheSavior** [comment]
Also, the reason React Native for Android doesn't support those shadow capabilities is because Android itself doesn't support that. Android only supports elevation. Since React Native renders to the platform views, that's what we can use. While that seems limiting, the other side of the same coin is that if you did use custom shadows, it wouldn't be consistent with other experiences on Android. Matching the experience of the platform is our team's top principle: https://reactnative.dev/blog/2020/07/17/react-native-principles#native-experience
