### ISSUE TITLE
About rn0.55.9, Android folding screen

### ISSUE THREAD

**Issue by lyb332442181** [react-native-community/discussions-and-proposals#431]
Hello, everyone. How to adapt the Android folding screen of rn0.55.9? Is it through monitoring JS callback, or can it be implemented by modifying the framework, or is it already supported in RN higher versions?

**Comment by p-syche** [comment]
Hello,

Newer RN versions recommend using `Dimensions` to handle foldable devices: https://reactnative.dev/docs/dimensions

It seems to me that on RN 0.55 you will have to implement your own event listener for dimension changes caused by folding a screen (https://archive.reactnative.dev/docs/0.55/dimensions#docsNav)
