### ISSUE TITLE
React Native for Foldable Device

### ISSUE THREAD

**Issue by faradorables** [react-native-community/discussions-and-proposals#488]
Hello, is there any library to support foldable devices? Currently, if I open my react native apps from folded state and then I unfolded the phone, the display is still shown like folded state and vice versa. Is there any way to fix it? Not to mention, the app will back to the front screen if the state is folded or unfolded

**Comment by hyochan** [comment]
@faradorables Hello this looks like an interesting discussion. I would like to test this.
Apart from that, there is a similar library in `react-native`, for supporting [window dual screen](https://support.microsoft.com/en-us/windows/set-up-dual-monitors-on-windows-3d5c15dc-cc63-d850-aeb6-b41778147554).

Since I feel like they have the similar behavior you may try [react-native-dualscreen](https://github.com/microsoft/react-native-dualscreen/tree/master/dualscreeninfo).

**Comment by faradorables** [comment]
@hyochan thank you for the answer! I will try to use the lib you mentioned. Hope it gonna work well :)
