### ISSUE TITLE
Migrating react-native-location to react-native-community

### ISSUE THREAD

**Issue by matt-oakes** [react-native-community/discussions-and-proposals#75]
I have recently taken over maintainership of the [`react-native-location`](https://github.com/timfpark/react-native-location) library and have been working to create a stable and cross-platform version in v2. You can see this work in the [`develop` branch](https://github.com/timfpark/react-native-location/tree/develop).

As mentioned in a [previous discussion](https://github.com/react-native-community/discussions-and-proposals/issues/63#issuecomment-445170156), I would like to migrate the project into the react-native-community organisation to avoid any issues around maintainership in the future.

What would the process currently look like to do this? I believe I would need @timfpark to actually do the migration as only the repository creator has those permissions on non-organisation repositories.

**Comment by sibelius** [comment]
I think we can bring more projects react-native related projects to react-native-community, so they don't stale

**Comment by kelset** [comment]
@sibelius I partly disagree with that phrase, react-native-community should not be a place to ‘park’ repositories ‘so they don’t stale’.

As mentioned in the other discussion, we are still discussing a proper flow & set of guidelines so I’d prefer to wait until those are set before migrating the lib.

During the holidays I’ll write up a proposal for those things so that we can discuss and eventually handle the migration in Jan.

**Comment by matt-oakes** [comment]
@kelset That's no problem. I'm not looking to "park" it, but I think it would be best to have it under community control for the future. 

I'll close this issue now and wait for the guidelines to land in the new year.

Thanks!

**Comment by vickywane** [comment]
Fingers crossed..
