### ISSUE TITLE
initialScrollIndex should have viewPosition

### ISSUE THREAD

**Issue by yernandus** [react-native-community/discussions-and-proposals#81]
### Introduction
 initialScrollIndex should have viewPosition parameter like scrollToIndex does.

**Comment by kelset** [comment]
👋 there - as stated in the README and the issue template, this repo is for long-form discussions. Yours seems more a precise feature request, so I suggest you use [Canny instead](https://react-native.canny.io/feature-requests).

But since the complexity is pretty high too, I suggest you develop this component on your own first.
